name: "Deploy first Workflow"

on:
  push:
    branches: ["main"]

jobs:
  first-job:
    runs-on: ubuntu-latest

    env:
      NAME: world
    steps:
      - name: "hola mundo"
        run: echo "set up environment $NAME"
      
  second-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: "hola mundo 2"
        run: echo "correr migraciones ${{ github.ref }}"