name: "Deploy first Workflow"

on:
  push:
    branches: ["main"]

jobs:
  first-job:
    runs-on: ubuntu-latest

    outputs:
      my_variable: ${{ steps.step_01.outputs.my_variable }}

    steps:
      - name: Generar archivo
        run: |
         echo "Archivo generado, hola" >> test.log
        
      - name: Subir artifactos
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test.log
        
  second-job:
    runs-on: ubuntu-latest

    steps:
      - name: Consumir artifactos
        uses: actions/download-artifact@v4
        with:
          name: test-artifact 

      - name: Mostrar contenido
        run: cat test.log
 