name: "Deploy first Workflow"

on:
  push:
    branches: ["main"]

jobs:
  first-job:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
      - name: print strategy matrix
        run: echo "Running on ${{ matrix.os }}"
        
        
     